# Radar Tracking System Configuration
# =================================

system:
  tracking_mode: "TWS"  # TWS or BEAM_REQUEST
  max_tracks: 1000
  update_rate_hz: 50
  
communication:
  primary:
    adapter_type: "UDP"
    host: "0.0.0.0"
    port: 8080
    buffer_size: 65536
    timeout_ms: 1000
  
algorithms:
  clustering:
    type: "DBSCAN"
    config_file: "config/algorithms/dbscan_config.yaml"
  association:
    type: "GNN"
    config_file: "config/algorithms/gnn_config.yaml"
  tracking:
    type: "IMM"
    config_file: "config/algorithms/imm_config.yaml"

track_management:
  confirmation_threshold: 3
  deletion_threshold: 5
  max_coast_time_sec: 10.0
  quality_threshold: 0.7
  
processing:
  thread_pool_size: 8
  queue_size_limit: 1000
  processing_timeout_ms: 100
  
output:
  hmi:
    enabled: true
    adapter_type: "UDP"
    host: "127.0.0.1"
    port: 9090
    update_rate_hz: 10
  fusion:
    enabled: true
    adapter_type: "TCP"
    host: "127.0.0.1"
    port: 9091
    update_rate_hz: 50
    
logging:
  level: "INFO"
  file_path: "logs/radar_tracking.log"
  max_file_size_mb: 100
  max_files: 10
  enable_data_logging: true
  data_log_path: "logs/data/"
  
performance:
  enable_monitoring: true
  log_interval_sec: 60
  enable_profiling: false